import { AcademicCapIcon } from '@heroicons/react/24/solid';
import type { User } from 'database';
import Head from 'next/head';
import { useState } from 'react';
import { ProductCard } from 'ui';

function Web() {
  const [users, setUsers] = useState<User>();
  const [loading, setLoading] = useState(false);

  const handleClick = async () => {
    setLoading(true);
    const response = await fetch('http://localhost:3333/api/v1/users');
    const data: User = await response.json();
    setUsers(data);
    setLoading(false);
  };

  return (
    <>
      <Head>
        <title>Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className="bg-red-500">Web</h1>

        <ProductCard />
        <p>
          {/* eslint-disable-next-line no-nested-ternary */}
          {loading
            ? 'Loading...'
            : users
            ? JSON.stringify(users, null, 2)
            : 'Click to fetch users'}
        </p>
      </div>
    </>
  );
}

export default Web;
