// import { AcademicCapIcon } from '@heroicons/react/24/solid';
import type { Product } from 'database';
import { IcActionsAdd, IcActionsStar, IcEcommerceBasket } from 'icons';
import Head from 'next/head';
import { useState } from 'react';
import { Button, ProductCard, Tag } from 'ui';

function Web() {
  const [data, setData] = useState<Product>();
  const [loading, setLoading] = useState(false);

  const handleClick = async () => {
    setLoading(true);
    const response = await fetch('http://localhost:3333/api/v1/products');
    const d: Product = await response.json();
    setData(d);
    setLoading(false);
  };

  return (
    <>
      <Head>
        <title>Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className="bg-red-500">Web</h1>
        <div className="flex">
          <IcActionsStar className=" w-4 h-4 fill-gray-900" />
          <IcActionsStar className="text-gray-500 w-4 h-4 " />
        </div>

        <IcEcommerceBasket className="text-red-500 w-16 h-16 " />
        <IcActionsAdd className="text-brown-500 w-16 h-16 " />
        <ProductCard
          title="Product"
          description="Somde description"
          price={39.99}
          oldPrice={49.99}
          currency="USD"
          rating={3}
        />
        <Tag text="Tag" appearance="secondary" size="sm" isCloseable />
        <p>
          {/* eslint-disable-next-line no-nested-ternary */}
          {loading
            ? 'Loading...'
            : data
            ? JSON.stringify(data, null, 2)
            : 'Click to fetch users'}
        </p>
      </div>
    </>
  );
}

export default Web;
